# MNIST Neural Network

In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [33]:
data = pd.read_csv('train.csv')

Taking in the data, with the dimensions being reflected in $m$ and $n$.
THis will also require us to shuffle the data since we can build a perfect model for this specific data set which may not work with other models or other dataset, or in a practical use case.

In [34]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_dev = data[:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:].T
Y_train = data_train[0]
X_train = data_train[1:n]

In [35]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(0, Z)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1)) 
    one_hot_Y[np.arange(Y.size), Y] = 1
    return one_hot_Y.T

def ReLU_deriv(Z):
    return Z > 0

def back_prop(Z1, A1, Z2, A2, W2, X, Y):
    m = Y.size
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1/m * dZ2.dot(A1.T)
    db2 = 1/m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1/m * dZ1.dot(X.T)
    db1 = 1/m * np.sum(dZ1)
    return dW1, dW2, db1, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    W2 = W2 - alpha * dW2
    b1 = b1 - alpha * db1
    b2 = b2 - alpha * db2
    return W1, W2, b1, b2

In [39]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size


def gradient_desc(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, dW2, db1, db2 = back_prop(Z1, A1, Z2, A2, W2, X, Y)
        W1, W2, b1, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if not(i % 100):
            print('Iteration: ', i)
            print('Accuracy: ', get_accuracy(get_predictions(A2), Y))
    return W1, b1, W2, b2

In [41]:
W1, b1, W2, b2 = gradient_desc(X_train, Y_train, 1000, 0.1)

C:\Users\Parth\AppData\Local\Temp\ipykernel_22368\4171746581.py:12: RuntimeWarning: overflow encountered in exp
  A = np.exp(Z) / sum(np.exp(Z))
C:\Users\Parth\AppData\Local\Temp\ipykernel_22368\4171746581.py:12: RuntimeWarning: overflow encountered in add
  A = np.exp(Z) / sum(np.exp(Z))
C:\Users\Parth\AppData\Local\Temp\ipykernel_22368\4171746581.py:12: RuntimeWarning: invalid value encountered in divide
  A = np.exp(Z) / sum(np.exp(Z))


Iteration:  0
[9 9 3 ... 2 3 9] [1 7 6 ... 0 1 5]
Accuracy:  0.1044390243902439
Iteration:  100
[0 0 0 ... 0 0 0] [1 7 6 ... 0 1 5]
Accuracy:  0.09821951219512196
Iteration:  200
[0 0 0 ... 0 0 0] [1 7 6 ... 0 1 5]
Accuracy:  0.09821951219512196
Iteration:  300
[0 0 0 ... 0 0 0] [1 7 6 ... 0 1 5]
Accuracy:  0.09821951219512196
Iteration:  400
[0 0 0 ... 0 0 0] [1 7 6 ... 0 1 5]
Accuracy:  0.09821951219512196
Iteration:  500
[0 0 0 ... 0 0 0] [1 7 6 ... 0 1 5]
Accuracy:  0.09821951219512196
Iteration:  600
[0 0 0 ... 0 0 0] [1 7 6 ... 0 1 5]
Accuracy:  0.09821951219512196
Iteration:  700
[0 0 0 ... 0 0 0] [1 7 6 ... 0 1 5]
Accuracy:  0.09821951219512196
Iteration:  800
[0 0 0 ... 0 0 0] [1 7 6 ... 0 1 5]
Accuracy:  0.09821951219512196
Iteration:  900
[0 0 0 ... 0 0 0] [1 7 6 ... 0 1 5]
Accuracy:  0.09821951219512196


KeyboardInterrupt: 